apps/body_composition/views.py
from flask import (
    Blueprint,
    flash,
    jsonify,
    redirect,
    render_template,
    request,
    url_for,
)
from flask_login import current_user, login_required
from sqlalchemy.exc import SQLAlchemyError
from werkzeug.wrappers import Response

from apps.body_composition.service import BodyCompositionService

from .forms import RecordBodyCompositionForm

blueprint = Blueprint(
    "body_composition",
    __name__,
    template_folder="templates",
    static_folder="static",
    url_prefix="/body_composition",
)


@blueprint.route("/record_body_composition", methods=["GET", "POST"])
@login_required
def record_body_composition() -> str | Response:
    user_id = current_user.id
    form = RecordBodyCompositionForm()

    if request.method == "GET":
        form_data = BodyCompositionService.init_form_data(user_id)
        form.weight.data = form_data["weight"]
        form.body_fat.data = form_data["body_fat"]
        return render_template(
            "body_composition/record_body_composition.html", form=form
        )

    if form.validate_on_submit():
        input_date = form.date.data
        weight = form.weight.data
        body_fat = form.body_fat.data

        try:
            BodyCompositionService.upsert(
                user_id, input_date, weight, body_fat
            )
            flash("Body composition data saved successfully.", "success")
            return redirect(url_for("main.index"))
        except (ValueError, TypeError) as e:
            flash(str(e), "danger")
        except SQLAlchemyError:
            flash(
                "Body composition record failed. Please try again later.",
                "danger",
            )

    return render_template(
        "body_composition/record_body_composition.html", form=form
    )


@blueprint.route("/get_body_composition_data", methods=["GET"])
def get_body_composition_data() -> Response:
    if current_user.is_authenticated:
        user_id = current_user.id
        body_composition_data = (
            BodyCompositionService.get_body_composition_dicts(user_id)
        )
    else:
        body_composition_data = BodyCompositionService.generate_sample_data()

    monthly_statistics = BodyCompositionService.compute_monthly_statistics(
        body_composition_data
    )

    return jsonify(
        body_composition_data,
        monthly_statistics,
    )

apps/views.py
from flask import Blueprint, render_template

blueprint = Blueprint(
    "main", __name__, template_folder="templates", static_folder="static"
)


@blueprint.route("/")
def index() -> str:
    return render_template("index.html")

apps/templates/_base.html
<!DOCTYPE html>
<html lang="en" data-bs-theme="auto">
    <head>
        <meta charset="utf-8" />
        <meta name="description"
              content="Track your diet, monitor body composition, and achieve your health goals with Diet App.">
        <meta name="keywords" content="Diet Health Training Fitness">
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <title>
            {% block title %}
            {% endblock title %}
        </title>
        <script src="{{ url_for('static', filename='color-modes.js') }}"></script>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css"
              rel="stylesheet"
              integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9"
              crossorigin="anonymous" />
        <link rel="stylesheet"
              href="{{ url_for('static', filename='color-modes.css') }}" />
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js"
                integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm"
                crossorigin="anonymous"
                defer></script>
        {% block extra_css %}
        {% endblock extra_css %}

        {% block extra_js %}
        {% endblock extra_js %}
    </head>
    <body>
        {% include "_header.html" %}

        <main class="container">
            {% with messages = get_flashed_messages(with_categories=true) %}
                {% if messages %}
                    <div class="flash-messages">
                        {% for category, message in messages %}
                            <div class="alert alert-{{ category }}">{{ message }}</div>
                        {% endfor %}
                    </div>
                {% endif %}
            {% endwith %}

            {% block content %}
            {% endblock content %}
        </main>

        {% include "_color_modes.html" %}
    </body>
</html>

apps/templates/_color_modes.html
<!-- 画像 -->
<svg xmlns="http://www.w3.org/2000/svg" class="d-none">
    <symbol id="check2" viewBox="0 0 16 16">
    <path d="M13.854 3.646a.5.5 0 0 1 0 .708l-7 7a.5.5 0 0 1-.708 0l-3.5-3.5a.5.5 0 1 1 .708-.708L6.5 10.293l6.646-6.647a.5.5 0 0 1 .708 0z" />
    </symbol>
    <symbol id="circle-half" viewBox="0 0 16 16">
    <path d="M8 15A7 7 0 1 0 8 1v14zm0 1A8 8 0 1 1 8 0a8 8 0 0 1 0 16z" />
    </symbol>
    <symbol id="moon-stars-fill" viewBox="0 0 16 16">
    <path d="M6 .278a.768.768 0 0 1 .08.858 7.208 7.208 0 0 0-.878 3.46c0 4.021 3.278 7.277 7.318 7.277.527 0 1.04-.055 1.533-.16a.787.787 0 0 1 .81.316.733.733 0 0 1-.031.893A8.349 8.349 0 0 1 8.344 16C3.734 16 0 12.286 0 7.71 0 4.266 2.114 1.312 5.124.06A.752.752 0 0 1 6 .278z" />
    <path d="M10.794 3.148a.217.217 0 0 1 .412 0l.387 1.162c.173.518.579.924 1.097 1.097l1.162.387a.217.217 0 0 1 0 .412l-1.162.387a1.734 1.734 0 0 0-1.097 1.097l-.387 1.162a.217.217 0 0 1-.412 0l-.387-1.162A1.734 1.734 0 0 0 9.31 6.593l-1.162-.387a.217.217 0 0 1 0-.412l1.162-.387a1.734 1.734 0 0 0 1.097-1.097l.387-1.162zM13.863.099a.145.145 0 0 1 .274 0l.258.774c.115.346.386.617.732.732l.774.258a.145.145 0 0 1 0 .274l-.774.258a1.156 1.156 0 0 0-.732.732l-.258.774a.145.145 0 0 1-.274 0l-.258-.774a1.156 1.156 0 0 0-.732-.732l-.774-.258a.145.145 0 0 1 0-.274l.774-.258c.346-.115.617-.386.732-.732L13.863.1z" />
    </symbol>
    <symbol id="sun-fill" viewBox="0 0 16 16">
    <path d="M8 12a4 4 0 1 0 0-8 4 4 0 0 0 0 8zM8 0a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 0zm0 13a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 13zm8-5a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2a.5.5 0 0 1 .5.5zM3 8a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2A.5.5 0 0 1 3 8zm10.657-5.657a.5.5 0 0 1 0 .707l-1.414 1.415a.5.5 0 1 1-.707-.708l1.414-1.414a.5.5 0 0 1 .707 0zm-9.193 9.193a.5.5 0 0 1 0 .707L3.05 13.657a.5.5 0 0 1-.707-.707l1.414-1.414a.5.5 0 0 1 .707 0zm9.193 2.121a.5.5 0 0 1-.707 0l-1.414-1.414a.5.5 0 0 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .707zM4.464 4.465a.5.5 0 0 1-.707 0L2.343 3.05a.5.5 0 1 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .708z" />
    </symbol>
</svg>

<!-- ドロップダウン -->
<div class="dropdown position-fixed bottom-0 end-0 mb-3 me-3 bd-mode-toggle">
    <button class="btn btn-bd-primary py-2 dropdown-toggle d-flex align-items-center"
            id="bd-theme"
            type="button"
            aria-expanded="false"
            data-bs-toggle="dropdown"
            aria-label="Toggle theme (auto)">
        <svg class="bi my-1 theme-icon-active" width="1em" height="1em">
            <use href="#circle-half"></use>
        </svg>
        <span class="visually-hidden" id="bd-theme-text">Toggle theme</span>
    </button>
    <ul class="dropdown-menu dropdown-menu-end shadow"
        aria-labelledby="bd-theme-text">
        <li>
            <button type="button"
                    class="dropdown-item d-flex align-items-center"
                    data-bs-theme-value="light"
                    aria-pressed="false">
                <svg class="bi me-2 opacity-50 theme-icon" width="1em" height="1em">
                    <use href="#sun-fill"></use>
                </svg>
                Light
                <svg class="bi ms-auto d-none" width="1em" height="1em">
                    <use href="#check2"></use>
                </svg>
            </button>
        </li>
        <li>
            <button type="button"
                    class="dropdown-item d-flex align-items-center"
                    data-bs-theme-value="dark"
                    aria-pressed="false">
                <svg class="bi me-2 opacity-50 theme-icon" width="1em" height="1em">
                    <use href="#moon-stars-fill"></use>
                </svg>
                Dark
                <svg class="bi ms-auto d-none" width="1em" height="1em">
                    <use href="#check2"></use>
                </svg>
            </button>
        </li>
        <li>
            <button type="button"
                    class="dropdown-item d-flex align-items-center active"
                    data-bs-theme-value="auto"
                    aria-pressed="true">
                <svg class="bi me-2 opacity-50 theme-icon" width="1em" height="1em">
                    <use href="#circle-half"></use>
                </svg>
                Auto
                <svg class="bi ms-auto d-none" width="1em" height="1em">
                    <use href="#check2"></use>
                </svg>
            </button>
        </li>
    </ul>
</div>

apps/templates/_form_fields.html
{{ form.hidden_tag() }}

{% for field in form %}
    {% if field.type not in ["CSRFTokenField", "SubmitField"] %}
        <div class="row">
            <div class="col-6">
                <div class="form-floating mb-3">
                    {{ field() }}
                    <label for="{{ field.id }}">{{ field.label }}</label>
                </div>

                {% if field.errors %}
                    <div class="text-danger">
                        {% for error in field.errors %}<p>{{ error }}</p>{% endfor %}
                    </div>
                {% endif %}
            </div>
        </div>
    {% endif %}

    {% if field.type == "SubmitField" %}
        <div class="mb-3">{{ field() }}</div>
    {% endif %}
{% endfor %}

apps/templates/_header.html
<header class="navbar navbar-expand-md">
    <a class="navbar-brand" href="{{ url_for('main.index') }}">Diet</a>

    <button class="navbar-toggler"
            type="button"
            data-bs-toggle="collapse"
            data-bs-target="#navbarNav"
            aria-controls="navbarNav"
            aria-expanded="false"
            aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav ms-auto">
            {% if current_user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link px-2" href="{{ url_for('main.index') }}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link px-2"
                       href="{{ url_for('body_composition.record_body_composition') }}">Record Body Composition</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link px-2" href="{{ url_for('auth.account_menu') }}">Account</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link px-2" href="{{ url_for('auth.signout') }}">Sign Out</a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link px-2" href="{{ url_for('auth.signup') }}">Sign Up</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link px-2" href="{{ url_for('auth.signin') }}">Sign In</a>
                </li>
            {% endif %}
        </ul>
    </div>
</header>

apps/templates/color_modes.html
<!-- 画像 -->
<svg xmlns="http://www.w3.org/2000/svg" class="d-none">
  <symbol id="check2" viewBox="0 0 16 16">
    <path
      d="M13.854 3.646a.5.5 0 0 1 0 .708l-7 7a.5.5 0 0 1-.708 0l-3.5-3.5a.5.5 0 1 1 .708-.708L6.5 10.293l6.646-6.647a.5.5 0 0 1 .708 0z"
    />
  </symbol>
  <symbol id="circle-half" viewBox="0 0 16 16">
    <path d="M8 15A7 7 0 1 0 8 1v14zm0 1A8 8 0 1 1 8 0a8 8 0 0 1 0 16z" />
  </symbol>
  <symbol id="moon-stars-fill" viewBox="0 0 16 16">
    <path
      d="M6 .278a.768.768 0 0 1 .08.858 7.208 7.208 0 0 0-.878 3.46c0 4.021 3.278 7.277 7.318 7.277.527 0 1.04-.055 1.533-.16a.787.787 0 0 1 .81.316.733.733 0 0 1-.031.893A8.349 8.349 0 0 1 8.344 16C3.734 16 0 12.286 0 7.71 0 4.266 2.114 1.312 5.124.06A.752.752 0 0 1 6 .278z"
    />
    <path
      d="M10.794 3.148a.217.217 0 0 1 .412 0l.387 1.162c.173.518.579.924 1.097 1.097l1.162.387a.217.217 0 0 1 0 .412l-1.162.387a1.734 1.734 0 0 0-1.097 1.097l-.387 1.162a.217.217 0 0 1-.412 0l-.387-1.162A1.734 1.734 0 0 0 9.31 6.593l-1.162-.387a.217.217 0 0 1 0-.412l1.162-.387a1.734 1.734 0 0 0 1.097-1.097l.387-1.162zM13.863.099a.145.145 0 0 1 .274 0l.258.774c.115.346.386.617.732.732l.774.258a.145.145 0 0 1 0 .274l-.774.258a1.156 1.156 0 0 0-.732.732l-.258.774a.145.145 0 0 1-.274 0l-.258-.774a1.156 1.156 0 0 0-.732-.732l-.774-.258a.145.145 0 0 1 0-.274l.774-.258c.346-.115.617-.386.732-.732L13.863.1z"
    />
  </symbol>
  <symbol id="sun-fill" viewBox="0 0 16 16">
    <path
      d="M8 12a4 4 0 1 0 0-8 4 4 0 0 0 0 8zM8 0a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 0zm0 13a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 13zm8-5a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2a.5.5 0 0 1 .5.5zM3 8a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2A.5.5 0 0 1 3 8zm10.657-5.657a.5.5 0 0 1 0 .707l-1.414 1.415a.5.5 0 1 1-.707-.708l1.414-1.414a.5.5 0 0 1 .707 0zm-9.193 9.193a.5.5 0 0 1 0 .707L3.05 13.657a.5.5 0 0 1-.707-.707l1.414-1.414a.5.5 0 0 1 .707 0zm9.193 2.121a.5.5 0 0 1-.707 0l-1.414-1.414a.5.5 0 0 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .707zM4.464 4.465a.5.5 0 0 1-.707 0L2.343 3.05a.5.5 0 1 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .708z"
    />
  </symbol>
</svg>

<!-- ドロップダウン -->
<div class="dropdown position-fixed bottom-0 end-0 mb-3 me-3 bd-mode-toggle">
  <button
    class="btn btn-bd-primary py-2 dropdown-toggle d-flex align-items-center"
    id="bd-theme"
    type="button"
    aria-expanded="false"
    data-bs-toggle="dropdown"
    aria-label="Toggle theme (auto)"
  >
    <svg class="bi my-1 theme-icon-active" width="1em" height="1em">
      <use href="#circle-half"></use>
    </svg>
    <span class="visually-hidden" id="bd-theme-text">Toggle theme</span>
  </button>
  <ul
    class="dropdown-menu dropdown-menu-end shadow"
    aria-labelledby="bd-theme-text"
  >
    <li>
      <button
        type="button"
        class="dropdown-item d-flex align-items-center"
        data-bs-theme-value="light"
        aria-pressed="false"
      >
        <svg class="bi me-2 opacity-50 theme-icon" width="1em" height="1em">
          <use href="#sun-fill"></use>
        </svg>
        Light
        <svg class="bi ms-auto d-none" width="1em" height="1em">
          <use href="#check2"></use>
        </svg>
      </button>
    </li>
    <li>
      <button
        type="button"
        class="dropdown-item d-flex align-items-center"
        data-bs-theme-value="dark"
        aria-pressed="false"
      >
        <svg class="bi me-2 opacity-50 theme-icon" width="1em" height="1em">
          <use href="#moon-stars-fill"></use>
        </svg>
        Dark
        <svg class="bi ms-auto d-none" width="1em" height="1em">
          <use href="#check2"></use>
        </svg>
      </button>
    </li>
    <li>
      <button
        type="button"
        class="dropdown-item d-flex align-items-center active"
        data-bs-theme-value="auto"
        aria-pressed="true"
      >
        <svg class="bi me-2 opacity-50 theme-icon" width="1em" height="1em">
          <use href="#circle-half"></use>
        </svg>
        Auto
        <svg class="bi ms-auto d-none" width="1em" height="1em">
          <use href="#check2"></use>
        </svg>
      </button>
    </li>
  </ul>
</div>

apps/templates/index.html
{% extends "_base.html" %}

{% block title %}
    Diet App
{% endblock title %}

{% block extra_js %}
    <script src="https://cdn.jsdelivr.net/npm/chart.js"defer></script>
    <script src="{{ url_for('static', filename='bodyCompositionVisualization.js') }}"
            defer></script>
{% endblock extra_js %}

{% block content %}
    <div class="row mb-3">
        <div class="col-6">
            <div class="form-floating">
                <select class="form-select" id="granularity-dropdown">
                    <option value="daily" selected>Daily</option>
                    <option value="monthly">Monthly</option>
                </select>
                <label for="granularity-dropdown">granularity</label>
            </div>
        </div>

        <div class="col-6">
            <div class="form-floating">
                <select class="form-select" id="duration-dropdown">
                    <option value="7">7 Days</option>
                    <option value="30" selected>30 Days</option>
                    <option value="90">90 Days</option>
                    <option value="180">180 Days</option>
                    <option value="365">1 Year</option>
                    <option value="1095">3 Years</option>
                </select>
                <label for="duration-dropdown">duration</label>
            </div>
        </div>
    </div>

    <canvas id="bodyCompositionGraph" class="mb-4"></canvas>

    <table id="body-composition-table"
           class="table table-striped table-bordered table-hover">
    </table>
{% endblock content %}

apps/templates/log_body_composition.html
{% extends 'base.html' %} {% block title %} 体重記録 - My Flask App {% endblock
%} {% block content %}

<h1>体重記録</h1>

<form method="POST" action="{{ url_for('main.log_body_composition') }}">
  {{ form.hidden_tag() }}

  <!-- 日付、体重と体脂肪率の入力欄 -->
  {% for field in [form.date, form.weight, form.body_fat] %}
  <div class="row">
    <div class="col-6">
      <div class="form-floating mb-3">
        {{ field(class="form-control", id=field.id) }}
        <label for="{{ field.id }}">{{ field.label.text }}</label>
      </div>
    </div>
  </div>
  {% endfor %}

  <!-- 記録ボタン -->
  <div class="mb-3">{{ form.submit(class="btn btn-primary") }}</div>
</form>

{% endblock %}

apps/templates/log_weight.html
{% extends 'base.html' %} {% block title %} 体重記録 - My Flask App {% endblock
%} {% block content %}
<h1>体重記録</h1>
<form method="POST" action="{{ url_for('main.log_weight') }}">
  {{ form.hidden_tag() }}
  <div>{{ form.date.label }} {{ form.date }}</div>
  <div>{{ form.weight.label }} {{ form.weight }}</div>
  <div>{{ form.body_fat.label }} {{ form.body_fat }}</div>
  <div>{{ form.submit }}</div>
</form>
{% endblock %}